fweber_backend:
    resource: "@fweberBackendBundle/Resources/config/routing.yml"
    prefix:   /backend
    options:
        expose: true

fweber_blog:
    resource: "@fweberBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

fweber_website:
    resource: "@fweberWebsiteBundle/Resources/config/routing.yml"
    prefix:   /

_user_bundle:
    resource: "@fweberUserBundle/Resources/config/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"