# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.text_extension:
        class: fweber\Twig\TextExtension
        public: false
        tags:
            - { name: twig.extension }
    app.app_extension:
            class: fweber\Twig\AppExtension
            public: false
            tags:
                - { name: twig.extension }