fweber\DataBundle\Entity\Post:
    properties:
        title:
            - NotBlank: ~
        slug:
            - NotBlank: ~
        text:
            - NotBlank: ~
        openDate:
            - DateTime: ~
        publishDate:
            - DateTime: ~
fweber\DataBundle\Entity\Category:
    properties:
        title:
            - NotBlank: ~