blog_posts:
    pattern: /
    defaults: { _controller: fweberBlogBundle:Blog:posts }

blog_post:
    pattern: /p/{slug}
    defaults: { _controller: fweberBlogBundle:Blog:post }

blog_tags:
    pattern: /tags
    defaults: { _controller: fweberBlogBundle:Blog:tags }

blog_tag:
    pattern: /tags/{slug}
    defaults: { _controller: fweberBlogBundle:Blog:tag }
