backend_index:
    pattern:  /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: backend_dashboard
        permanent: true

backend_dashboard:
    pattern:  /dashboard
    defaults: { _controller: fweberBackendBundle:Page:dashboard }

backend_posts:
    resource:   "@fweberBackendBundle/Resources/config/Post/routing.yml"
    prefix:     /posts

backend_tags:
    resource:   "@fweberBackendBundle/Resources/config/Category/routing.yml"
    prefix:     /tags

backend_users:
    resource:   "@fweberBackendBundle/Resources/config/User/routing.yml"
    prefix:     /users
