backend_posts_collection:
    pattern:  /
    defaults: { _controller: fweberBackendBundle:Post:collection }

backend_posts_create:
    pattern:  /add
    defaults: { _controller: fweberBackendBundle:Post:create }

backend_posts_preview:
    pattern:  /{postId}/preview
    defaults: { _controller: fweberBackendBundle:Post:preview }

backend_posts_update:
    pattern:  /{postId}/edit
    defaults: { _controller: fweberBackendBundle:Post:update }

backend_posts_delete:
    pattern:  /{postId}/delete
    defaults: { _controller: fweberBackendBundle:Post:delete }

backend_posts_publish:
    pattern:  /{postId}/publish
    defaults: { _controller: fweberBackendBundle:Post:publish }

backend_posts_draft:
    pattern:  /{postId}/draft
    defaults: { _controller: fweberBackendBundle:Post:draft }