index:
    path: /
    defaults: { _controller: fweberWebsiteBundle:Page:index }

portfolio:
    path: /portfolio
    defaults: { _controller: fweberWebsiteBundle:Page:portfolio }

music:
    path: /music
    defaults: { _controller: fweberWebsiteBundle:Page:music }

imprint:
    path: /imprint
    defaults: { _controller: fweberWebsiteBundle:Page:imprint }
